{% set name = "naiad" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/naiad/naiad/-/archive/{{ version }}/naiad-{{ version }}.tar.gz
  sha256: 725ba8e25cef6bab867e6229cf637626768ce3a2df33155c50a99db06b757a72

build:
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python
  entry_points:
    - naiad-create-index = naiad.cli.create:main
    - naiad-inspect-csv = naiad.cli.csv:main
    - naiad-search = naiad.cli.search:main
    - naiad-crossover-search = naiad.cli.crosssearch:main
    - naiad-register = naiad.cli.storing:main
    - naiad-inquire = naiad.cli.inquire:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - wheel
    - setuptools
    - poetry
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >={{ python_min }}
    - pyyaml >=6.0.0,<6.1
    - pydantic-cli >=4.3.0,<4.4
    - elasticsearch >=7.13.4,<7.14
    - shapely >=1.7.1
    - python-dateutil
    - spherical-geometry >=1.2.22
    - naiad-commons

test:
  requires:
    - python {{ python_min }}
  imports:
    - naiad

about:
  home: https://gitlab.ifremer.fr/naiad/naiad
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: A suite of backend tools in python for indexing, searching and colocating EO data.

extra:
  recipe-maintainers:
    - marie59
